package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/SDK-E/dnser/internal/config"
)

const branded503 = `<!DOCTYPE html><html><head><title>dnser</title></head><body style="background:#082003;color:#2cdb16;font-family:system-ui;display:flex;align-items:center;justify-content:center;height:100vh;margin:0"><div style="text-align:center"><h1 style="font-size:3rem;margin:0">Zzz</h1><p>This project is asleep or restarting. The first request wakes it up.</p></div></body></html>`

type caddySite struct {
	Address   string
	Directive []string
}

func renderCaddyfile(m *config.Manifest, names []string, primary string, port int, ctx config.PlaceholderCtx) ([]byte, error) {
	var sites []caddySite
	for _, name := range names {
		site, err := renderSite(m, name, port, ctx)
		if err != nil {
			return nil, fmt.Errorf("site %s: %w", name, err)
		}
		sites = append(sites, site)
	}
	for i, r := range m.Routes {
		if r.Host == "" {
			continue
		}
		site, err := renderHostRouteSite(m, i, r, ctx)
		if err != nil {
			return nil, fmt.Errorf("route site %s: %w", r.Host, err)
		}
		sites = append(sites, site)
	}
	sort.SliceStable(sites, func(i, j int) bool { return sites[i].Address < sites[j].Address })

	var b strings.Builder
	b.WriteString("# generated by dnser; edits are overwritten\n")
	for _, s := range sites {
		b.WriteString("\n" + caddyQuoteAddr(s.Address) + " {\n")
		for _, d := range s.Directive {
			for _, line := range strings.Split(strings.TrimRight(d, "\n"), "\n") {
				b.WriteString("\t" + line + "\n")
			}
		}
		b.WriteString("}\n")
	}
	return []byte(b.String()), nil
}

func renderSite(m *config.Manifest, name string, port int, ctx config.PlaceholderCtx) (caddySite, error) {
	httpsEnabled := httpsForName(m, name)
	addr := name
	if !httpsEnabled {
		addr = "http://" + name
	}
	site := caddySite{Address: addr}
	if httpsEnabled {
		site.Directive = append(site.Directive, "tls internal")
	}
	if port > 0 {
		site.Directive = append(site.Directive, pathRouteDirectives(m)...)
		site.Directive = append(site.Directive, fmt.Sprintf("reverse_proxy 127.0.0.1:%d", port))
	}
	if port == 0 && !hasAnyPortRoute(m) {
		site.Directive = append(site.Directive, branded503Directive())
	}
	raw, err := rawCaddyDirectives(m, ctx)
	if err != nil {
		return site, err
	}
	site.Directive = append(site.Directive, raw...)
	site.Directive = append(site.Directive, errorHandlingDirective(port, hasAnyPortRoute(m)))
	return site, nil
}

func renderHostRouteSite(m *config.Manifest, idx int, r config.Route, ctx config.PlaceholderCtx) (caddySite, error) {
	site := caddySite{Address: r.Host}
	if httpsForName(m, r.Host) {
		site.Directive = append(site.Directive, "tls internal")
	}
	target := r.Backend
	if target == "" && r.Port != nil {
		target = fmt.Sprintf("127.0.0.1:%d", *r.Port)
	}
	site.Directive = append(site.Directive, fmt.Sprintf("reverse_proxy %s", target))
	site.Directive = append(site.Directive, errorHandlingDirective(0, true))
	return site, nil
}

func pathRouteDirectives(m *config.Manifest) []string {
	var out []string
	for _, r := range m.Routes {
		if r.Path == "" || r.Port == nil {
			continue
		}
		out = append(out, fmt.Sprintf("handle %s {\n\treverse_proxy 127.0.0.1:%d\n}", r.Path, *r.Port))
	}
	return out
}

func hasAnyPortRoute(m *config.Manifest) bool {
	for _, r := range m.Routes {
		if r.Port != nil {
			return true
		}
	}
	return false
}

func httpsForName(m *config.Manifest, name string) bool {
	if m.HTTPS.PerName != nil {
		if v, ok := m.HTTPS.PerName[name]; ok {
			return v
		}
		if v, ok := m.HTTPS.PerName["*."+name]; ok {
			return v
		}
		return true
	}
	return m.HTTPS.Enabled || !m.HTTPS.Set
}

func branded503Directive() string {
	return heredocRespond(branded503)
}

func heredocRespond(body string) string {
	return fmt.Sprintf("respond <<HTML\n%s\nHTML 503", body)
}

func errorHandlingDirective(port int, hasRoutes bool) string {
	if port == 0 && !hasRoutes {
		return ""
	}
	return "handle_errors {\n\t" + strings.ReplaceAll(heredocRespond(branded503), "\n", "\n\t") + "\n}"
}

func rawCaddyDirectives(m *config.Manifest, ctx config.PlaceholderCtx) ([]string, error) {
	if m.Caddy == nil || len(m.Caddy.Value) == 0 {
		return nil, nil
	}
	substituted, err := config.SubstituteStrings(m.Caddy.Value, ctx)
	if err != nil {
		return nil, fmt.Errorf("caddy placeholders: %w", err)
	}
	rawMap, ok := substituted.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("caddy raw merge must be a mapping")
	}
	out := make([]string, 0, len(rawMap))
	routeIdx := 0
	for _, key := range sortedKeys(rawMap) {
		if key == "handle" {
			rendered, consumed, err := renderHandleRoutes(rawMap[key], &routeIdx)
			if err != nil {
				return nil, fmt.Errorf("caddy.%s: %w", key, err)
			}
			out = append(out, rendered...)
			if consumed {
				continue
			}
		}
		line, err := renderRawTopLevel(key, rawMap[key])
		if err != nil {
			return nil, fmt.Errorf("caddy.%s: %w", key, err)
		}
		out = append(out, line)
	}
	return out, nil
}

var matcherModules = map[string]bool{
	"path": true, "method": true, "header": true, "host": true,
	"query": true, "expression": true, "not": true, "file": true,
	"protocol": true, "remote_ip": true, "local_ip": true,
}

func renderHandleRoutes(value any, routeIdx *int) ([]string, bool, error) {
	items, ok := value.([]any)
	if !ok {
		return nil, false, nil
	}
	allMaps := len(items) > 0
	for _, item := range items {
		if _, isMap := item.(map[string]any); !isMap {
			allMaps = false
			break
		}
	}
	if !allMaps {
		return nil, false, nil
	}
	var out []string
	for _, item := range items {
		elem := item.(map[string]any)
		var matcherLines, handlerLines []string
		hasMatcher := false
		for _, sub := range sortedKeys(elem) {
			if matcherModules[strings.ToLower(sub)] && scalarOrScalarList(elem[sub]) {
				body, err := renderBlockBody(map[string]any{sub: elem[sub]}, 1)
				if err != nil {
					return nil, false, err
				}
				matcherLines = append(matcherLines, body)
				hasMatcher = true
				continue
			}
			body, err := renderDirective(sub, elem[sub], 1)
			if err != nil {
				return nil, false, err
			}
			handlerLines = append(handlerLines, body)
		}
		name := fmt.Sprintf("@dnser_route_%d", *routeIdx)
		*routeIdx++
		if hasMatcher {
			out = append(out, fmt.Sprintf("%s {\n%s\n}", name, strings.Join(matcherLines, "\n")))
			out = append(out, fmt.Sprintf("handle %s {\n%s\n}", name, indentLines(strings.Join(handlerLines, "\n"), 1)))
		} else {
			out = append(out, fmt.Sprintf("handle {\n%s\n}", indentLines(strings.Join(handlerLines, "\n"), 1)))
		}
	}
	return out, true, nil
}

func scalarOrScalarList(v any) bool {
	switch t := v.(type) {
	case string, int, float64, bool:
		return true
	case []any:
		for _, e := range t {
			switch e.(type) {
			case string, int, float64, bool:
			default:
				return false
			}
		}
		return true
	default:
		return false
	}
}

func indentLines(s string, depth int) string {
	pad := strings.Repeat("\t", depth)
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		lines[i] = pad + l
	}
	return strings.Join(lines, "\n")
}

func renderRawTopLevel(key string, value any) (string, error) {
	if strings.HasPrefix(key, "@") {
		body, err := renderBlockBody(value, 1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s {\n%s\n}", key, body), nil
	}
	return renderDirective(key, value, 0)
}

func renderDirective(key string, value any, depth int) (string, error) {
	pad := strings.Repeat("\t", depth)
	switch v := value.(type) {
	case map[string]any:
		body, err := renderBlockBody(v, depth+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s%s {\n%s\n%s}", pad, key, body, pad), nil
	case []any:
		var lines []string
		for _, elem := range v {
			switch e := elem.(type) {
			case map[string]any:
				body, err := renderBlockBody(e, depth+1)
				if err != nil {
					return "", err
				}
				lines = append(lines, fmt.Sprintf("%s%s {\n%s\n%s}", pad, key, body, pad))
			default:
				lines = append(lines, fmt.Sprintf("%s%s %s", pad, key, caddyToken(elem)))
			}
		}
		if len(lines) == 0 {
			return "", fmt.Errorf("empty list")
		}
		return strings.Join(lines, "\n"), nil
	default:
		return fmt.Sprintf("%s%s %s", pad, key, caddyToken(value)), nil
	}
}

func renderBlockBody(value any, depth int) (string, error) {
	pad := strings.Repeat("\t", depth)
	switch v := value.(type) {
	case map[string]any:
		if folded, ok := foldOutputDirective(v); ok {
			return pad + folded, nil
		}
		var lines []string
		for _, sub := range sortedKeys(v) {
			rendered, err := renderSubKey(pad, sub, v[sub])
			if err != nil {
				return "", err
			}
			lines = append(lines, rendered)
		}
		return strings.Join(lines, "\n"), nil
	case []any:
		var lines []string
		for _, elem := range v {
			switch e := elem.(type) {
			case map[string]any:
				var inner []string
				for _, sub := range sortedKeys(e) {
					rendered, err := renderSubKey(pad, sub, e[sub])
					if err != nil {
						return "", err
					}
					inner = append(inner, rendered)
				}
				lines = append(lines, strings.Join(inner, "\n"))
			default:
				lines = append(lines, pad+caddyToken(e))
			}
		}
		return strings.Join(lines, "\n"), nil
	default:
		return pad + caddyToken(value), nil
	}
}

func foldOutputDirective(m map[string]any) (string, bool) {
	outVal, has := m["output"]
	if !has {
		return "", false
	}
	module, isScalar := outVal.(string)
	if !isScalar || module == "" {
		return "", false
	}
	var args []string
	for _, sub := range sortedKeys(m) {
		if sub == "output" {
			continue
		}
		switch t := m[sub].(type) {
		case string:
			args = append(args, caddyToken(t))
		case int, float64, bool:
			args = append(args, caddyToken(t))
		case []any:
			for _, e := range t {
				switch e.(type) {
				case string, int, float64, bool:
					args = append(args, caddyToken(e))
				default:
					return "", false
				}
			}
		default:
			return "", false
		}
	}
	line := "output " + module
	if len(args) > 0 {
		line += " " + strings.Join(args, " ")
	}
	return line, true
}

func renderSubKey(pad, sub string, value any) (string, error) {
	switch v := value.(type) {
	case map[string]any:
		body, err := renderBlockBody(v, depthOf(pad)+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s%s {\n%s\n%s}", pad, sub, body, pad), nil
	case []any:
		tokens := make([]string, 0, len(v))
		allScalar := true
		for _, elem := range v {
			if _, isMap := elem.(map[string]any); isMap {
				allScalar = false
				break
			}
			tokens = append(tokens, caddyToken(elem))
		}
		if allScalar {
			return pad + sub + " " + strings.Join(tokens, " "), nil
		}
		var lines []string
		for _, elem := range v {
			m, ok := elem.(map[string]any)
			if !ok {
				lines = append(lines, pad+sub+" "+caddyToken(elem))
				continue
			}
			body, err := renderBlockBody(m, depthOf(pad)+1)
			if err != nil {
				return "", err
			}
			lines = append(lines, fmt.Sprintf("%s%s {\n%s\n%s}", pad, sub, body, pad))
		}
		return strings.Join(lines, "\n"), nil
	default:
		return pad + sub + " " + caddyToken(value), nil
	}
}

func depthOf(pad string) int {
	return strings.Count(pad, "\t")
}

func caddyToken(v any) string {
	s := fmt.Sprint(v)
	if s == "" || strings.ContainsAny(s, " \t\"'{}#$") {
		return fmt.Sprintf("%q", s)
	}
	return s
}

func caddyQuoteAddr(addr string) string {
	if strings.Contains(addr, " ") {
		return fmt.Sprintf("%q", addr)
	}
	return addr
}
